{{- if and .Values.backend.migrations.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "personal-site.fullname" . }}-backend-migrations
  labels:
    {{- include "personal-site.componentLabels" (dict "component" "backend" "context" $) | nindent 4 }}
data:
{{ (.Files.Glob "files/backend-migrations/*.sql").AsConfig | nindent 2 }}
{{- end }}
