apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
