{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "personal-site.postgresql.serviceName" . }}
  labels:
    {{- include "personal-site.componentLabels" (dict "component" "postgresql" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "personal-site.componentSelectorLabels" (dict "component" "postgresql" "context" $) | nindent 4 }}
{{- end }}
