apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@postgresql:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}?schema=public
  {{- else if .Values.backendSecrets.databaseUrl }}
  DATABASE_URL: {{ .Values.backendSecrets.databaseUrl | quote }}
  {{- end }}
  JWT_SECRET: {{ .Values.backendSecrets.jwtSecret | quote }}
  {{- if .Values.backendSecrets.corsOrigin }}
  CORS_ORIGIN: {{ .Values.backendSecrets.corsOrigin | quote }}
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  MONGODB_USER: {{ .Values.mongodb.auth.username | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.password | quote }}
  MONGODB_URI: mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@mongodb:{{ .Values.mongodb.port }}/personal-site?authSource=admin
  {{- end }}
